## 1 X V100-32 GB GPU 
batch_type: length
batch_bins: 10000000
## Workhorse 
##batch_bins: 4000000
accum_grad: 1
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
log_interval: 1000
freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 1024
    normalize_before: false
    freeze_finetune_updates: 1000
    # if use espent-trained model
    # if use downloaded model:
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_large_ll60k.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_large_ll60k.pt

decoder: seq_classifier 
decoder_conf:
    pool_type: mean
    # attention_heads: 4
    # attention_dim: 64
    # dropout_rate: 0.1

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.15
    length_normalized_loss: false
    disable_add_sos_eos: true 

optim: adam
optim_conf:
    lr: 0.001
    
val_scheduler_criterion:
- valid
- acc
early_stopping_criterion:
- valid
- acc
- max

best_model_criterion:
-   - valid
    - acc
    - max
scheduler: reducelronplateau
scheduler_conf:
        mode: min
        factor: 0.5
        

unused_parameters: true
frontend: null
normalize: null
specaug: null
