batch_type: length
#batch_bins: 25000000
#batch_bins: 6000000
batch_bins: 100000
accum_grad: 1
max_epoch: 100
patience: none
# The initialization method for model parameters
init: xavier_uniform
best_model_criterion:
-   - valid
    - acc
    - max
keep_nbest_models: 10
log_interval: 10000
freeze_param: [
    "encoder.encoders.mask_emb", "encoder.encoders.feature_extractor",
    "encoder.encoders.post_extract_proj", "encoder.encoders.encoder.pos_conv",
]

input_size: 1
encoder: hubert
encoder_conf:
    output_size: 768
    normalize_before: false
    freeze_finetune_updates: 10000
    # if use espent-trained model
    # if use downloaded model:
    hubert_url: https://dl.fbaipublicfiles.com/hubert/hubert_base_ls960.pt
    hubert_dir_path: ./downloads/hubert_pretrained_models/hubert_base_ls960.pt

decoder: seq_classifier 
decoder_conf:
    pool_type: mean
    # attention_heads: 4
    # attention_dim: 64
    # dropout_rate: 0.1

model_conf:
    ctc_weight: 0.0
    lsm_weight: 0.15
    length_normalized_loss: false
    disable_add_sos_eos: true 

optim: adam
optim_conf:
    lr: 0.001
    
val_scheduler_criterion:
- valid
- acc
early_stopping_criterion:
- valid
- acc
- max

best_model_criterion:
-   - valid
    - acc
    - max
scheduler: warmuplr
scheduler_conf:
       warmup_steps : 1500 
        

unused_parameters: true


frontend: null

normalize: null

specaug: null
